name: Build, Push and Deploy to Cloud Run

on: [push]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.JSON_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/cicd-thomas/cicd-artifact-thomas/cicd-thomas:latest .

      - name: Push Docker image
        run: |
          docker push europe-west1-docker.pkg.dev/cicd-thomas/cicd-artifact-thomas/cicd-thomas:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cicd-thomas-deployment
          image: europe-west1-docker.pkg.dev/cicd-thomas/cicd-artifact-thomas/cicd-thomas:latest
          region: europe-west1
