name: Deploy to Cloud Run

on: [push]

jobs:
  deploy:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.JSON_KEY }}'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cicd-thomas-deployment
          image: europe-west1-docker.pkg.dev/cicd-thomas/cicd-artifact-thomas/cicd-thomas:latest
          region: europe-west1
