name: Build and Push Docker Image

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.JSON_KEY }}'

    - name: Configure Docker to use Google Cloud Artifact Registry
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t europe-west1-docker.pkg.dev/cicd-thomas/cicd-artifact-thomas/cicd-thomas:latest .
        docker push europe-west1-docker.pkg.dev/cicd-thomas/cicd-artifact-thomas/cicd-thomas:latest
