name: Lint Dockerfile

on: [push]

jobs:
  lint-dockerfile:
    name: Run Hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v2
        with:
          dockerfile: Dockerfile

      - name: Fail if issues found
        run: exit 1
