name: Lint Python Code

on: [push]

jobs:
  lint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt || true  # Ignore if no requirements

      - name: Run pylint
        run: |
          pylint **/*.py --fail-under=7 --disable=C,R0801
